package com.cjm.ms;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.function.Executable;

import static org.junit.jupiter.api.Assertions.*;

/*
- Generated by pressing alt-enter on BankAccount class.
- Set JUnit to compile in Project Structure > Modules > Dependencies.
- You can run all test cases by clicking on the arrow next to the class name.
 */
class BankAccountTest {
    private BankAccount account;
    private static int count;

    // @BeforeAll marks a method that runs before any test case to initialise
    // test environment. The method must be static.
    @BeforeAll
    public static void beforeAll() {
        System.out.println("This method executes once, before all test cases. Count: " + count);
        count++;
    }
    // @BeforeEach marks a method that runs before each test case.
    @BeforeEach
    public void beforeEach() {
        account = new BankAccount("John", "Doe", 1000.00);
        System.out.println("Running test...");
    }
    // @Test marks a test method. These methods are automatically
    // called at runtime. Test methods must be public void.
    @Test
    public void getBalance_deposit() { // Test cases should be descriptive.
        // Assertions.fail() automatically fails the test case.
        // fail("This test has yet to be implemented.");
        //BankAccount account = new BankAccount("John", "Doe", 1000.00);
        account.deposit(200.00, true);
        assertEquals(1200.00, account.getBalance(), 0.001);
    }
    @Test
    public void getBalance_withdraw() {
        // Every method is instantiating a BankAccount instance.
        // To reduce code duplication it should be moved to
        // an @Before method that sets up the test environment.
        // BankAccount account = new BankAccount("John", "Doe", 1000.00);
        account.withdraw(200.00, true);
        assertEquals(800.00, account.getBalance(), 0.001);
    }
    @Test
    void isChecking_true() {
        // BankAccount account = new BankAccount("John", "Doe", 1000.00);
        // Boolean specific version of assertEquals().
        assertTrue(account.isChecking());
    }
    @Test
    public void deposit() {
        // fail("This test has yet to be implemented.");
        // BankAccount account = new BankAccount("John", "Doe", 1000.00);
        double balance = account.deposit(200.00, true);
        // Assertions add constraints to specify what constitutes a pass.
        // In this case 1200 = balance.
        assertEquals(1200.00, balance, 0.001);
    }
    @Test
    public void withdraw_ATM() {
        // This will throw an exception, but that is intended functionality and
        // should pass the test.
        Executable exec = () -> account.withdraw(600.00, false);
        assertThrows(IllegalArgumentException.class, exec);
    }
    @Test
    public void withdraw_branch() {
        double balance = account.withdraw(600.00, true);
        assertEquals(400.00, balance, 0.01);
    }
    /*
    @Test
    public void dummyTest() {
        // Can run this test case independently by clicking on the arrow next to the
        // test method. As such tests should run independent to other test cases.
        // assertEquals() passes if the arguments are equal, otherwise it fails.
        assertEquals(20, 21); // Fails because 20 != 21.
    }
    */
    // @AfterAll marks a method that runs after all test cases to release resources.
    @AfterAll
    public static void afterAll() {
        System.out.println("This method executes once, after all test cases. Count: " + count);
        count++;
    }
    // @AfterEach marks a method that runs after each test case.
    @AfterEach
    public void afterEach() {
        System.out.println("Count: " + count);
        count++;
    }
}